galaxy_info:
  author: Andrey Gubarev <andrey@andreygubarev.com> (andreygubarev.com)
  description: Ansible role for setting up Tailscale client
  company: andreygubarev

  license: MIT

  min_ansible_version: '7.0.0'

  platforms: []
  # platforms:
  # - name: Ubuntu
  #   versions:
  #   - focal

  galaxy_tags: []

dependencies: []
